Bump version following addition of 0.1 to pkgsrc-wip
git-svn-id: file:///home/bacon/SVN/pkg-dev/pkg-dev-0.2@78 6b304774-fb49-e211-8a70-0017315c2eee

diff --git a/Scripts/pbulk-setup b/Scripts/pbulk-setup
--- a/Scripts/pbulk-setup
+++ b/Scripts/pbulk-setup
@@ -103,6 +103,11 @@ if [ `whoami` != root ]; then
     exit 1
 fi
 
+if ! which cvs; then
+    printf "No cvs command in PATH.  Please install cvs and try again.\n"
+    exit 1
+fi
+
 cat << EOM
 
 $0 should only be run in a chroot, VM, or on a system that is
@@ -132,14 +137,64 @@ The var and pkgdb directories will also be located under this prefix.
 EOM
 
 pkgsrc=`auto_ask source-prefix 'Pkgsrc source directory?' /usr/pkgsrc`
+parent=`dirname $pkgsrc`
+suffix=${pkgsrc##/*pkgsrc}
 if [ ! -e $pkgsrc ]; then
-    printf "$pkgsrc does not exist.  Please download and extract pkgsrc first.\n"
-    exit 1
+    printf "Download and unpack pkgsrc? y/[n] "
+    read download
+    if [ 0$download = 0y ]; then
+	quarter=`auto_ask quarter 'Quarter? [e.g. 2017Q3 or current]' current`
+	if [ 0$quarter = 0current ]; then
+	    url=ftp://ftp.netbsd.org/pub/pkgsrc/$quarter/pkgsrc.tar.gz
+	else
+	    url=ftp://ftp.netbsd.org/pub/pkgsrc/pkgsrc-$quarter/pkgsrc.tar.gz
+	fi
+	if which curl; then
+	    curl -O $url
+	elif which fetch; then
+	    fetch $url
+	elif which wget; then
+	    wget $url
+	else
+	    printf "No curl, fetch, or wget found.  :-(\n"
+	    exit 1
+	fi
+	start_dir=`pwd`
+	umask 022           # Make sure source tree is world readable
+	mkdir -p $parent
+	cd $parent
+	tar zxvf $start_dir/pkgsrc.tar.gz
+	if [ 0$quarter != 0current ]; then
+	    mv pkgsrc `basename $pkgsrc`
+	fi
+	cd $start_dir
+    else
+	printf "Aborting...\n"
+	exit 1
+    fi
 fi
 
-prefix=`auto_ask bin-prefix 'Pkgsrc install prefix?' /usr/pkg`
+# Get latest patches
+printf "Update pkgsrc tree? [y]/n "
+read update
+if [ 0$update != 0n ]; then
+    save_cwd=`pwd`
+    cd $pkgsrc
+    cvs -q up -dP
+    cd $save_cwd
+fi
 
-# pbulk_dir=`auto_ask pbulk-prefix 'Pbulk install prefix?' /usr/pbulk`
+prefix=`auto_ask bin-prefix 'Pkgsrc install prefix?' $parent/pkg$suffix`
+
+pbulk_dir=`auto_ask pbulk-prefix 'Pbulk install prefix?' $parent/pbulk$suffix`
+
+cat << EOM
+
+Some packages that are thought to be make job safe will fail to build when
+make jobs are set too high, so a max value of 4 or maybe 8 is recommended
+to minimize build failures.
+
+EOM
 
 make_jobs=`auto_ask make-jobs 'Max # processes for make to use?' 4`
 
@@ -150,6 +205,8 @@ if [ 0$rsync_user != 0 ]; then
 	release=${release%%.*}
 	release=${release##*release }
 	os=RHEL$release
+    elif [ `uname` = Darwin ]; then
+	os=$(uname)$(uname -r | cut -d . -f 1)
     else
 	os=$(uname)-$(uname -r)
     fi
@@ -162,8 +219,18 @@ pbulk_user=`auto_ask pbulk-user 'User to run pbulk builds?' pbulk`
 pbulk_group=`auto_ask pbulk-group 'Group to run pbulk builds?' pbulk`
 
 # Set up env for this tree
-PATH=/usr/bin:/usr/sbin:/bin:/sbin
+PATH=/usr/bin:/usr/sbin:/bin:/sbin:/opt/pkg/bin:/opt/pkg/sbin:/usr/pkg/bin:/usr/pkg/sbin
 export PATH
+unset LD_LIBRARY_PATH
+
+case `uname` in
+FreeBSD|NetBSD)
+    fetch_cmd=fetch
+    ;;
+*)
+    fetch_cmd=curl
+    ;;
+esac
 
 # Make sure $pbulk_user user can access everything
 umask 022
@@ -172,8 +239,7 @@ umask 022
 # permissions for security reasons.
 chmod 1777 /tmp /var/tmp
 
-# Copy root ssh in case keys are installed on rsync target
-mkdir -p /root
+chmod -R a+rX $pkgsrc
 
 # Remove existing prefix.  It may not have been created by our bootstrap
 # script and therefore may not have the correct permissions and options.
@@ -183,35 +249,128 @@ rm -rf $prefix
 # Redirect workdir or it will use the pkgsrc tree outside the chroot
 
 cat << EOM > /mk-pbulk.conf
-#!/bin/sh -e
-
 # Written by $0
 
 SKIP_LICENSE_CHECK=         yes
 ALLOW_VULNERABLE_PACKAGES=  yes
 PKG_DEVELOPER=              yes
 X11_TYPE=                   modular
-FETCH_USING=                curl
+FETCH_USING=                $fetch_cmd
 MAKE_JOBS=                  $make_jobs
 WRKOBJDIR=                  /tmp/pkgbuild
 EOM
 
 cat << EOM > /mk-pkg.conf
-#!/bin/sh -e
-
 # Written by $0
 
 SKIP_LICENSE_CHECK=         yes
 ALLOW_VULNERABLE_PACKAGES=  yes
 PKG_DEVELOPER=              yes
 X11_TYPE=                   modular
-FETCH_USING=                curl
+FETCH_USING=                $fetch_cmd
 MAKE_JOBS=                  $make_jobs
+PKGSRC_FORTRAN=             gfortran
 WRKOBJDIR=                  /tmp/pkgbuild
+PKGSRC_USE_FORTIFY=         no
 EOM
 
-mkdir -p /pbulk
-cat << EOM > /pbulk/bootstrap
+if [ `uname` != NetBSD ]; then
+    cat << EOM >> /mk-pkg.conf
+PREFER_NATIVE=              no
+PREFER_PKGSRC=              yes
+EOM
+fi
+
+# FIXME: Verify that this is the minimal list of $base_gcc deps
+# Pkgsrc 2017Q2 assumes a c++11 compiler.  Force CentOS 6 to build everything
+# using a pkgsrc GCC instead of its native GCC 4.4.7, which has only partial
+# c++11 support and does not support the -std=c++11 flag.
+# Hopefully pkgsrc will handle cases like this automatically in the near
+# future and this hack will no longer be needed.
+if [ `uname` = Linux ]; then
+
+    cat << EOM
+    
+Select a minimum GCC version.  Many packages will not build with older
+GCC suites such as the GCC 4.4 provided by RHEL/CentOS 6.  When you select
+a newer compiler here, a pkgsrc gcc will be used to build all packages
+except itself.
+
+1.. 4.8
+2.. 4.9
+3.. 5.0
+4.. 6.0
+5.. 7.0
+
+EOM
+    printf "Selection? [3] "
+    read selection
+    if [ 0$selection = 0 ]; then
+	selection=3
+    fi
+    case $selection in
+    1)
+	base_gcc=gcc48
+	gcc_version=4.8
+	;;
+    2)
+	base_gcc=gcc49
+	gcc_version=4.9
+	;;
+    3)
+	base_gcc=gcc5
+	gcc_version=5.0
+	;;
+    4)
+	base_gcc=gcc6
+	gcc_version=6.0
+	;;
+    5)
+	base_gcc=gcc7
+	gcc_version=7.0
+	;;
+    esac
+
+    cat << EOM >> /mk-pkg.conf
+
+.if \
+    empty(PKGPATH:Marchivers/bzip2) && \\
+    empty(PKGPATH:Marchivers/pax) && \\
+    empty(PKGPATH:Marchivers/xz) && \\
+    empty(PKGPATH:Mconverters/help2man) && \\
+    empty(PKGPATH:Mconverters/p5-Unicode-EastAsianWidth) && \\
+    empty(PKGPATH:Mdevel/autoconf) && \\
+    empty(PKGPATH:Mdevel/gettext-lib) && \\
+    empty(PKGPATH:Mdevel/gettext-tools) && \\
+    empty(PKGPATH:Mdevel/gmp) && \\
+    empty(PKGPATH:Mdevel/gtexinfo) && \\
+    empty(PKGPATH:Mdevel/libtool-base) && \\
+    empty(PKGPATH:Mdevel/m4) && \\
+    empty(PKGPATH:Mdevel/ncurses) && \\
+    empty(PKGPATH:Mdevel/nbpatch) && \\
+    empty(PKGPATH:Mdevel/p5-gettext) && \\
+    empty(PKGPATH:Mlang/$base_gcc) && \\
+    empty(PKGPATH:Mlang/$base_gcc-libs) && \\
+    empty(PKGPATH:Mlang/perl5) && \\
+    empty(PKGPATH:Mmath/cloog) && \\
+    empty(PKGPATH:Mmath/isl) && \\
+    empty(PKGPATH:Mmath/mpcomplex) && \\
+    empty(PKGPATH:Mmath/mpfr) && \\
+    empty(PKGPATH:Mmisc/p5-Locale-libintl) && \\
+    empty(PKGPATH:Mpkgtools/cwrappers) && \\
+    empty(PKGPATH:Mpkgtools/digest) && \\
+    empty(PKGPATH:Mpkgtools/pkg_install-info) && \\
+    empty(PKGPATH:Msysutils/checkperms) && \\
+    empty(PKGPATH:Mtextproc/p5-Text-Unidecode)
+
+GCC_REQD+=$gcc_version
+
+.endif  # GCC_REQD
+EOM
+fi
+
+mkdir -p $pbulk_dir
+cat << EOM > $pbulk_dir/bootstrap
 #!/bin/sh -e
 
 # Written by $0
@@ -225,33 +384,42 @@ cat << EOM > /pbulk/bootstrap
 umask 022
 
 # Create pbulk user
-useradd -c 'pbulk user' -m -s /bin/sh $pbulk_user || true
+case `uname` in
+Linux|NetBSD)
+    if ! grep -q "^${pbulk_group}:" /etc/group; then
+	groupadd $pbulk_group
+    fi
+    if ! grep -q "^${pbulk_user}:" /etc/passwd; then
+	useradd -c 'pbulk user' -m -g $pbulk_group -s /bin/sh $pbulk_user
+    fi
+    ;;
+esac
 
-PATH=/pbulk/bin:$PATH
+PATH=$pbulk_dir/bin:$PATH
 export PATH
 
-if [ ! -e /pbulk/bin/bmake ]; then
-    cd /sharedapps/pkgsrc-2017Q1/bootstrap
+if [ ! -e $pbulk_dir/bin/bmake ]; then
+    cd $pkgsrc/bootstrap
     ./bootstrap \\
 	--abi=64 \\
 	--make-jobs=$make_jobs \\
-	--prefix=/pbulk \\
-	--varbase=/pbulk/var \\
+	--prefix=$pbulk_dir \\
+	--varbase=$pbulk_dir/var \\
 	--prefer-pkgsrc=yes \\
 	--mk-fragment=/mk-pbulk.conf \\
 	--workdir=/tmp/pbulk-bootstrap
     ./cleanup
 fi
 
-cd /sharedapps/pkgsrc-2017Q1/pkgtools/pbulk
+cd $pkgsrc/pkgtools/pbulk
 bmake install
 
 # Create the package building prefix and create a bootstrap kit, just a
 # tarball of prefix with nothing installed but bmake.  The bulk build will
 # wipe prefix and recreate it from this tarball before each build.
 
-if [ ! -e /sharedapps/pkg-2017Q1/bin/bmake ]; then
-    cd /sharedapps/pkgsrc-2017Q1/bootstrap
+if [ ! -e $prefix/bin/bmake ]; then
+    cd $pkgsrc/bootstrap
     ./bootstrap \\
 	--abi=64 \\
 	--make-jobs=$make_jobs \\
@@ -266,32 +434,33 @@ fi
 cd /
 mkdir -p bulklog
 chown -Rh ${pbulk_user}:$pbulk_group $prefix $pkgsrc/packages /tmp/pkgbuild
-tar zcvf /pbulk/bootstrap.tar.gz .$prefix
+tar zcvf $pbulk_dir/bootstrap.tar.gz .$prefix
 
 # Generate a pbulk.list file.  Users can add whatever packages they want
 # to this.
 
-cat << EOM2 > /pbulk/etc/pbulk.list
+cat << EOM2 > $pbulk_dir/etc/pbulk.list
 pkgtools/digest
 EOM2
 
 # Update pbulk.conf with some reasonable defaults for this build.
 
-cat << EOM2 >> /pbulk/etc/pbulk.conf
+cat << EOM2 >> $pbulk_dir/etc/pbulk.conf
 
 ################################################################
 # Overrides from $0
 
-# PATH=/pbulk/bin:$PATH
-# export PATH
+# Scrub path
+PATH=/usr/bin:/usr/sbin:/bin:/sbin:/opt/pkg/bin:/opt/pkg/sbin:/usr/pkg/bin:/usr/pkg/sbin
+export PATH
 
 # https://pkgsrc.joyent.com/docs/bulk/
 # Limit processes to an hour of CPU time.  Anything which takes longer than
 # this is most probably broken.
 ulimit -t 3600
 
-bootstrapkit=/pbulk/bootstrap.tar.gz
-limited_list=/pbulk/etc/pbulk.list
+bootstrapkit=$pbulk_dir/bootstrap.tar.gz
+limited_list=$pbulk_dir/etc/pbulk.list
 reuse_scan_results=yes
 unprivileged_user=$pbulk_user
 make=$prefix/bin/bmake
@@ -318,20 +487,38 @@ EOM2
 EOM
 
 if [ 0$rsync_user != 0 ]; then
-    cat << EOM >> /pbulk/bootstrap
-cat << EOM2 >> /pbulk/etc/pbulk.conf
+    cat << EOM >> $pbulk_dir/bootstrap
+cat << EOM2 >> $pbulk_dir/etc/pbulk.conf
 pkg_rsync_target="$rsync_user@$rsync_host:$rsync_pkg_dir"
 report_rsync_target="$rsync_user@$rsync_host:$rsync_report_dir"
-rsync=/pbulk/bin/rsync
+rsync=$pbulk_dir/bin/rsync
 EOM2
 EOM
+    echo "Authorizing ${rsync_user}@$(hostname) on $rsync_host."
+
+    if [ ! -f $HOME/.ssh/id_rsa.pub ] ; then
+       ssh-keygen -P "" -f "$HOME/.ssh/id_rsa"
+    fi
+
+    key=`cat $HOME/.ssh/id_rsa.pub`
+    ssh ${rsync_user}@$rsync_host "umask 022; mkdir -p .ssh; touch .ssh/known_hosts .ssh/authorized_keys; chmod 600 .ssh/authorized_keys; ssh-keygen -R $(hostname) && echo $key >> .ssh/authorized_keys"
+    ssh ${rsync_user}@$rsync_host mkdir -p $rsync_pkg_dir
+    ssh ${rsync_user}@$rsync_host mkdir -p $rsync_report_dir
 else
-cat << EOM >> /pbulk/bootstrap
-printf "rsync=:\n" >> /pbulk/etc/pbulk.conf
+    cat << EOM >> $pbulk_dir/bootstrap
+printf "rsync=:\n" >> $pbulk_dir/etc/pbulk.conf
 EOM
 fi
 
-chmod 755 /pbulk/bootstrap
+cat << EOM >> $pbulk_dir/bootstrap
+printf "Bootstrap done.  You may now run $pbulk_dir/bin/bulkbuild.\n"
+EOM
+
+chmod 755 $pbulk_dir/bootstrap
+
+if ! [ -e $HOME/.ssh/id_rsa ]; then
+    ssh-keygen -b 2048 -t rsa
+fi
 
 # Inform the user what to do next.
 
@@ -339,11 +526,11 @@ cat << EOM
 
 Now run
 
-/pbulk/bootstrap
+$pbulk_dir/bootstrap
 
-Then edit /pbulk/etc/pbulk.conf and /pbulk/etc/pbulk.list to taste 
+Then edit $pbulk_dir/etc/pbulk.conf and $pbulk_dir/etc/pbulk.list to taste 
 and finally run
 
-/pbulk/bin/bulkbuild
+$pbulk_dir/bin/bulkbuild
 
 EOM
diff --git a/Scripts/pkg-grep b/Scripts/pkg-grep
--- a/Scripts/pkg-grep
+++ b/Scripts/pkg-grep
@@ -2,14 +2,15 @@
 
 ##########################################################################
 #   Script description:
-#       Search files in port frameworks.
+#       Search files in pkgsrc frameworks.
 #
-#       This is the same script as pkg-grep in the pkg-dev tools.
-#       Be sure to keep them in sync!
+#   Note:
+#       Keep in sync with port-grep!
 #
 #   Arguments:
-#       -p prefix (default /usr/ports)
+#       -p pkgsrc-dir (default /usr/ports)
 #       -f file (default Makefile)
+#       -v (echo categories during search)
 #
 #   History:
 #   Date        Name        Modification
@@ -18,7 +19,7 @@
 
 usage()
 {
-    printf "Usage: $0 [-p prefix] [-f file] regular-expression [grep flags]\n"
+    printf "Usage: $0 [-p pkgsrc-dir] [-f file] [-v] regular-expression [grep flags]\n"
     exit 1
 }
 
@@ -27,10 +28,12 @@ usage()
 #   Main
 ##########################################################################
 
-if [ `basename $0` = port-grep ]; then
-    prefix=/usr/ports
+if which pkg_add; then
+    pkg_add=`which pkg_add`
+    pkgsrc=`echo ${pkg_add%/sbin/pkg_add} | sed -e 's|pkg|pkgsrc|g'`
 else
-    prefix=/usr/pkgsrc
+    printf "Cannot determine pkgsrc pkgsrc-dir.\n"
+    exit 1
 fi
 
 # Overwrite later if provided as an argument
@@ -39,13 +42,17 @@ filename='Makefile'
 while [ 0`echo $1 | cut -c 1-1` = 0'-' ]; do
     case "$1" in
     -p)
-	prefix=$2
+	pkgsrc=$2
 	shift
 	shift
 	;;
     -f)
 	filename="$2"
 	shift
+	shift
+	;;
+    -v)
+	verbose=1
 	shift
 	;;
     *)
@@ -63,11 +70,12 @@ shift
 grep_flags="$@"
 
 set +e
-cd $prefix
+cd $pkgsrc
 for category in *; do
     if [ -e $category/Makefile ] && [ $category != Templates ]; then
-	printf "Searching $category...\n"
+	if [ 0$verbose = 01 ]; then
+	    printf "Searching $category...\n"
+	fi
 	grep $grep_flags "$re" $category/*/$filename
     fi
 done
-
