pkg-pbulk-setup: Convert to be run inside chroot
git-svn-id: file:///home/bacon/SVN/pkg-dev/pkg-dev-0.1@43 6b304774-fb49-e211-8a70-0017315c2eee

diff --git a/Scripts/pkg-pbulk-setup b/Scripts/pkg-pbulk-setup
--- a/Scripts/pkg-pbulk-setup
+++ b/Scripts/pkg-pbulk-setup
@@ -22,6 +22,75 @@ usage()
 
 
 ##########################################################################
+#   Function description:
+#       
+#   Arguments:
+#       
+#   Returns:
+#       
+#   History:
+#   Date        Name        Modification
+#   2017-05-16  root        Begin
+##########################################################################
+
+auto_ask()
+{
+    if [ $# != 3 ]; then
+	cat << EOM > /dev/stderr
+Usage: $0 tag "question" default-answer
+
+    'tag' is a name used to uniquely identify this question in the
+    recorded responses.  It must be a single word without spaces or
+    special shell characters, and must be unique across all calls
+    to $0.
+    
+    'question' must be enclosed in quotes if it contains spaces or
+    special characters.
+    
+    'default-answer' must also be encloded in quotes if it contains
+    spaces or special characters.
+
+EOM
+	exit 1
+    fi
+
+    tag=$1
+    question="$2"
+    
+    response_file=auto-ask-responses.txt
+    touch $response_file
+    
+    default_response="`awk -F'|' '$1 == "'$tag'" { print $2 }' $response_file`"
+    if [ 0"$default_response" = 0 ]; then
+	default_response="$3"
+    fi
+    
+    valid=0
+    while [ $valid = 0 ]; do
+	printf "$question [$default_response] " > /dev/stderr
+	read resp
+	# resp cannot contain '|'
+	if echo "$resp" | fgrep '|'; then
+	    printf "Sorry, responses cannot contain '|'.\n" > /dev/stderr
+	else
+	    valid=1
+	fi
+    done
+    
+    if [ 0"$resp" = 0 ]; then
+	resp="$default_response"
+    fi
+    
+    awk -F'|' '$1 != "'$tag'" { print $0 }' $response_file > $response_file.temp
+    mv -f $response_file.temp $response_file
+    printf "${tag}|${resp}\n" >> $response_file
+    
+    printf "$resp\n"
+    return 0
+}
+
+
+##########################################################################
 #   Main
 ##########################################################################
 
@@ -32,6 +101,51 @@ fi
 if [ `whoami` != root ]; then
     printf "$0 must be run by root.\n"
     exit 1
+fi
+
+cat << EOM
+
+$0 should only be run in a chroot, VM, or on a system that is
+dedicated exclusively to pbulk builds.  It will remove all installed
+packages and perform extensive reconfiguration of your system.
+
+To create a chroot directory, do one of the following:
+
+1.
+    a.  Install pkgtools/mksandbox.
+    b.  mkdir -p chroot-os-version
+	mksandbox --without-x --without-src chroot-os-version
+    c.  /path/to/chroot-os-version/sandbox mount
+
+2.  Perform a minimal OS installation and create a tarball to be unpacked
+    and used as the chroot env.  A virtual machine can be used for this.
+    
+    For CentOS/RHEL:
+    
+    a.  Install from the -minimal ISO image.
+    b.  Run the following in the new installation:
+	cd /
+	mkdir tar
+	tar zcvf tar/os-version.tgz \
+	    --exclude ./tar --exclude ./proc --exclude ./dev .
+    c.  Copy tar/os-version.tgz to a bare-metal installation of the same OS.
+    d.  Run the following on the bare-metal installation:
+	mkdir chroot-os-version
+	cd chroot-os-version
+	tar zxvf /path/to/os-version.tar.gz
+	cd ..
+	pkg-start-chroot /path/to/chroot-os-version
+    
+3.  Copy pkg-pbulk-setup to chroot-os-version.
+4.  Inside the sandbox, bootstrap a pkgsrc tree (e.g. using auto-pkgsrc-setup)
+    and then run pkg-pbulk-setup and follow the instructions on the screen.
+
+EOM
+
+printf "Continue? yes/[no] "
+read continue
+if [ 0$continue != 0yes ]; then
+    exit
 fi
 
 cat << EOM
@@ -48,11 +162,15 @@ The var and pkgdb directories will also be located under this prefix.
 
 EOM
 
-pkgsrc=`auto-ask source-prefix 'Pkgsrc source directory?' /usr/pkgsrc`
-prefix=`auto-ask bin-prefix 'Pkgsrc install prefix?' /usr/pkg`
-pbulk_dir=`auto-ask pbulk-dir 'Sandbox directory?' $prefix/pbulk`
+pkgsrc=`auto_ask source-prefix 'Pkgsrc source directory?' /usr/pkgsrc`
+if [ ! -e $pkgsrc ]; then
+    printf "$pkgsrc does not exist.  Please download and extract pkgsrc first.\n"
+    exit 1
+fi
 
-rsync_user=`auto-ask rsync-user 'rsync username (leave blank if you do not want to upload packages)?' ''`
+prefix=`auto_ask bin-prefix 'Pkgsrc install prefix?' /usr/pkg`
+
+rsync_user=`auto_ask rsync-user 'rsync username (leave blank if you do not want to upload packages)?' ''`
 if [ 0$rsync_user != 0 ]; then
     if [ -e /etc/redhat-release ]; then
 	release=`cat /etc/redhat-release`
@@ -62,51 +180,29 @@ if [ 0$rsync_user != 0 ]; then
     else
 	os=$(uname)$(uname -r | cut -d '.' -f 1)
     fi
-    rsync_host=`auto-ask rsync-host 'rsync hostname?' ''`
-    rsync_pkg_dir=`auto-ask rsync-pkg-dir 'rsync pkg directory?' "www/pkgsrc/packages$prefix/$os"`
-    rsync_report_dir=`auto-ask rsync-report-dir 'rsync report directory?' "www/pkgsrc/reports$prefix/$os"`
+    rsync_host=`auto_ask rsync-host 'rsync hostname?' ''`
+    rsync_pkg_dir=`auto_ask rsync-pkg-dir 'rsync pkg directory?' "www/pkgsrc/packages$prefix/$os"`
+    rsync_report_dir=`auto_ask rsync-report-dir 'rsync report directory?' "www/pkgsrc/reports$prefix/$os"`
 fi
 
 # Set up env for this tree
-source $prefix/etc/pkgsrc.sh
+PATH=/usr/bin:/usr/sbin:/bin:/sbin
+export PATH
 
 # Make sure pbulk user can access everything
 umask 022
 
-# Use bmake if it's in PATH
-if which bmake; then
-    make=bmake
-else
-    make=make
-fi
-
-if [ ! -d $pbulk_dir ]; then
-    printf "Create $pbulk_dir with mksandbox? y/[n] "
-    read mksandbox
-    if [ 0$mksandbox = 0y ]; then
-	if ! which mksandbox; then
-	    cd $pkgsrc/pkgtools/mksandbox
-	    $make install
-	fi
-	
-	# Create chroot dir from pkgsrc tree
-	mkdir -p $pbulk_dir
-	mksandbox --without-x --without-src $pbulk_dir
-    fi
-fi
-
 # Copy root ssh in case keys are installed on rsync target
-mkdir -p $pbulk_dir/root
-cp -Rp /root/.ssh $pbulk_dir/root
+mkdir -p /root
 
 # Remove existing prefix.  It may not have been created by our bootstrap
 # script and therefore may not have the correct permissions and options.
-rm -rf $pbulk_dir$prefix
+rm -rf $prefix
 
 # Generate mk.conf fragments
 # Redirect workdir or it will use the pkgsrc tree outside the chroot
 
-cat << EOM > $pbulk_dir/mk-pbulk.conf
+cat << EOM > /mk-pbulk.conf
 #!/bin/sh -e
 
 SKIP_LICENSE_CHECK=         yes
@@ -118,7 +214,7 @@ MAKE_JOBS=                  4
 WRKOBJDIR=                  /tmp/pkgbuild
 EOM
 
-cat << EOM > $pbulk_dir/mk-pkg.conf
+cat << EOM > /mk-pkg.conf
 #!/bin/sh -e
 
 SKIP_LICENSE_CHECK=         yes
@@ -130,7 +226,7 @@ MAKE_JOBS=                  4
 WRKOBJDIR=                  /tmp/pkgbuild
 EOM
 
-cat << EOM > $pbulk_dir/bootstrap
+cat << EOM > /bootstrap
 #!/bin/sh -e
 
 # Redirect workdir or it will use the pkgsrc tree outside the chroot
@@ -232,7 +328,7 @@ EOM2
 EOM
 
 if [ 0$rsync_user != 0 ]; then
-    cat << EOM >> $pbulk_dir/bootstrap
+    cat << EOM >> /bootstrap
 cat << EOM2 >> /usr/pbulk/etc/pbulk.conf
 pkg_rsync_target="$rsync_user@$rsync_host:$rsync_pkg_dir"
 report_rsync_target="$rsync_user@$rsync_host:$rsync_report_dir"
@@ -240,12 +336,12 @@ rsync=/usr/pbulk/bin/rsync
 EOM2
 EOM
 else
-cat EOM >> $pbulk_dir/bootstrap
+cat << EOM >> /bootstrap
 printf "rsync=:\n" >> /usr/pbulk/etc/pbulk.conf
 EOM
 fi
 
-chmod 755 $pbulk_dir/bootstrap
+chmod 755 /bootstrap
 
 # Inform the user what to do next.
 
@@ -253,12 +349,11 @@ cat << EOM
 
 Now run
 
-chroot $pbulk_dir /bin/sh
 ./bootstrap
 
 Then edit /usr/pbulk/etc/pbulk.conf and /usr/pbulk/etc/pbulk.list to taste 
 and finally run
 
-$pbulk_dir/bin/bulkbuild
+/usr/pbulk/bin/bulkbuild
 
 EOM
