Clean up pkg-remake
git-svn-id: file:///home/bacon/SVN/pkg-dev/pkg-dev-0.1@26 6b304774-fb49-e211-8a70-0017315c2eee

diff --git a/Scripts/pkg-remake b/Scripts/pkg-remake
--- a/Scripts/pkg-remake
+++ b/Scripts/pkg-remake
@@ -60,8 +60,12 @@ printf "Regenerate $plist? (y/[n]) "
 read regen_plist
 
 if [ 0$regen_plist = 0'y' ]; then
-    mv -f $plist $plist.old
-    ${make} install
+    if [ -e $plist ] && [ ! -e $plist.old ]; then
+	mv -f $plist $plist.old
+    fi
+    printf '@comment $NetBSD$\n' > PLIST
+    # If PKG_DEVELOPER=yes, make install will fail on incorrect PLIST
+    ${make} install || true
     ${make} print-PLIST > $plist
     if diff -u $plist.old $plist; then
 	printf "No changes to $plist\n"
